unclassified:
  location:
    url: http://127.0.0.1:8080/
jenkins:
  systemMessage: "Controlled by Configuration as Code"
jobs:
  - script: >
  	multibranchPipelineJob('configuration-as-code') {
      	branchSources {
          	git {
              	id = 'configuration-as-code'
              	remote('https://github.com/jenkinsci/configuration-as-code-plugin.git')
          	}
      }
}
